name: llama-finetune
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.2.0
  - torchvision=0.17.0
  - torchaudio=2.2.0
  - pytorch-cuda=11.8
  - numpy>=1.24.0
  - pandas>=2.0.0
  - scikit-learn>=1.3.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - tqdm>=4.65.0
  - pip
  - pip:
      - transformers>=4.36.0
      - datasets>=2.15.0
      - accelerate>=0.24.0
      - wandb>=0.16.0
      - peft>=0.7.0
      - bitsandbytes>=0.41.0
      - "unsloth[torch]"
      - flask
